services:
  neo4j:
    container_name: "ifg_kg_db"
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_default__database: ifg
      NEO4J_AUTH: neo4j/test
    volumes:
      - neo4j_data:/data
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ifgproduz743
      POSTGRES_DB: ifg_produz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .docker/postgres/scripts/:/docker-entrypoint-initdb.d/
      - ./storage/ifg_produz/ifg_produz010721.backup:/dumps/ifg_produz010721.backup


volumes:
  postgres_data:
  neo4j_data: