services:
  neo4j:
    container_name: "ifg_kg_db"
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_default__database: ifg
      NEO4J_AUTH: neo4j/test
      TZ: America/Sao_Paulo
    volumes:
      - neo4j_data:/data
  postgres:
    container_name: "ifg_produz_db"
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${IFG_PRODUZ_DB_PASSWORD}
      POSTGRES_DB: ${IFG_PRODUZ_DB_DATABASE}
    ports:
      - "${IFG_PRODUZ_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .docker/postgres/scripts/:/docker-entrypoint-initdb.d/
      - ./storage/ifg_produz/ifg_produz010721.backup:/dumps/ifg_produz010721.backup


volumes:
  postgres_data:
  neo4j_data: