services:
  neo4j:
    container_name: "ifgproduz_neo4j"
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_default__database: ifg
      NEO4J_AUTH: neo4j/test
